config/routes.rb
Railstest::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  resources :tickets
  
    
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  namespace :admin do
    root "base#index"

    resources :users do
      resources :tickets, only: [:new, :create]
    end

    resources :tickets, except: [:new, :create]
  end
  
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include Capitalize

  belongs_to :user
  after_save :subscribe_mailchimp
  before_validation :capitalize_names
  after_update :unsubscribe_mailchimp
  before_destroy :unsubscribe_mailchimp

  # Strip whitespaces
  auto_strip_attributes :first_name, :last_name

  # Validations
  validates :first_name, :last_name, :email, :user_id, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :wristband_id, uniqueness: true, allow_nil: true

  # Pagination
  paginates_per 100

  def self.paged(page_number)
    order(id: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      q = "%#{search}%"
      joins(:user).where('tickets.first_name LIKE ? OR tickets.last_name LIKE ? OR tickets.wristband_id LIKE ? 
			 OR tickets.email LIKE ? OR users.email LIKE ?', q, q, q, q, q).order(id: :asc).page page_number
    else
      order(id: :asc).page page_number
    end
  end

  def self.last_ticket_purchases(count)
    order(created_at: :desc).limit(count)
  end

  private
    def unsubscribe_mailchimp
      # remove from mailing list asynchronously with Sidekiq
      MailchimpUnsubscriber.perform_async(self.email_was, "attendees_list")
    end

    def subscribe_mailchimp
      # add to mailing list asynchronously with Sidekiq
      MailchimpSubscriber.perform_async(self[:id], "attendees_list")
    end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  

  def index
    @tickets = Ticket.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_ticket_path(params[:id])
  end
  
  def edit
  end

  def new
    @ticket = Ticket.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @ticket = Ticket.new(ticket_params.merge(user: @user))
    if @ticket.valid?
      @ticket.save
      redirect_to admin_tickets_path, notice: "#{@ticket.user.email}'s ticket created."
    else
      @errors = @ticket.errors
      flash.now[:error] = @errors.full_messages[0]
      render 'new'
    end
  end
  
  def update
    if @ticket.update_attributes(ticket_params)
      redirect_to admin_tickets_path, notice: "#{@ticket.user.email}'s ticket updated."
    else
      @errors = @ticket.errors
      flash.now[:error] = @errors.full_messages[0]
      render 'edit'
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "#{@ticket.first_name}'s ticket deleted."
    redirect_to admin_tickets_path
  end
  
  
  private 
  
  def set_ticket
    @ticket = Ticket.find(params[:id])
  rescue
    flash[:alert] = "The ticket with an id of #{params[:id]} doesn't exist."
    redirect_to admin_tickets_path
  end
  
  def ticket_params
    params.require(:ticket).permit(
    :first_name,
    :last_name,
    :email,
    :wristband_id
    )
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!

  def index
    @ticket_num = 0
  end

  def edit
    @ticket = current_user.tickets[params[:id].to_i]
    check_ticket_exists()
    @id = params[:id]
  end

  def update
    @ticket = current_user.tickets[params[:id].to_i]
    check_ticket_exists()
    @id = params[:id]

    if @ticket.update_attributes(ticket_params)
      flash[:notice] = "Ticket updated!"
      redirect_to tickets_path
    else 
      @errors = @ticket.errors
      flash.now[:error] = @errors.full_messages[0]
      render 'edit'
    end
  end

  def create
    @curr_tickets = current_user.tickets.size
    @num_tickets = params[:tickets].size
    @discount = 0
    @tickets = []
    
    if current_user.college == "st-hughs" && current_user.tickets.size == 0 then @discount = 500 end
    
    if @num_tickets + @curr_tickets > User::MAX_TICKETS
      flash[:error] = "You can only buy #{User::MAX_TICKETS} tickets."
      return redirect_to tickets_path
    end

    params[:tickets].each_value do |ticket|
      @t = current_user.tickets.new(first_name: ticket["first_name"][" "],
                                    last_name: ticket["last_name"][" "], email: ticket["email"][" "])
      if @t.valid?
        @tickets += [@t]
      else
        flash[:error] = "Your tickets details were problematic. You weren't charged."
        return redirect_to tickets_path
      end
    end

    @amount = 9000 * @num_tickets - @discount

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :card  => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => current_user.email,
      :currency    => 'gbp'
    )

    for t in @tickets
      t.save(validate:false)
    end

    # add to mailing list asynchronously with Sidekiq
    MailchimpSubscriber.perform_async(@current_user.id, "post_purchase_list")

    redirect_to tickets_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      return redirect_to tickets_path
  end

  def new
  end

  private
    def ticket_params
      params.require(:ticket).permit(:first_name, :last_name, :email)
    end
   
    def check_ticket_exists
      if !@ticket then 
        flash[:error] = "You don't have that many tickets."
        redirect_to tickets_path
      end
    end
end

app/views/tickets/_ticket.html.erb
<li> <%= ticket.first_name %> <%= ticket.last_name %> <font size="2"> <%= link_to "Edit", edit_ticket_path(id: @ticket_num) %> </font> </li> <% @ticket_num = @ticket_num + 1 %>

app/views/tickets/edit.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1>Edit ticket</h1>
      <%= form_for @ticket, url: {:action => "update", :id => @id}, html: { id: "ticketEdit" + @id } do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <div class="row">
            <div class="col-sm-8">
              <%= f.text_field :first_name, :autofocus => true, class: "form-control" %>
            </div>
          </div>
        </div>
  
        <div class="form-group">
          <%= f.label :last_name %>
          <div class="row">
            <div class="col-sm-8">
              <%= f.text_field :last_name, :autofocus => true, class: "form-control" %>
            </div>
          </div>
        </div>
  
        <div class="form-group">
          <%= f.label :email %>
          <div class="row">
            <div class="col-sm-8">
              <%= f.text_field :email, :autofocus => true, class: "form-control" %>
            </div>
          </div>
        </div>
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      <% end %>
  </div>
</div>

app/views/tickets/index.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>
<%= javascript_include_tag "ticket" %>
<%= stylesheet_link_tag "ticket", media: "all", "data-turbolinks-track" => true %>

<% curr_tickets = current_user.tickets.size; max_tickets = User::MAX_TICKETS %>

<div class="row">
  <div class="col-sm-12">
    <h1>Tickets</h1>
  </div>
    <div class="container">
    <div class="col-sm-7">
      <h3>New Tickets </h3>
      <% if curr_tickets  >= max_tickets %>
        <%= content_tag "p", id: "ticketInfo", data: {
          email: current_user.email,
          discount: 0,
          curr_tickets: curr_tickets,
          max_tickets: max_tickets
        } do %>
          You've already bought <strong> <%= curr_tickets %> </strong> tickets, and can't buy any more. We look forwards to seeing you at St Hugh's Ball.
        <% end %>
      <% else %>
        <%= content_tag "p", id: "ticketInfo", data: { 
          email: current_user.email,
          discount: (current_user.college == "st-hughs" && curr_tickets == 0) ? 500 : 0, 
          curr_tickets: curr_tickets,
          max_tickets: max_tickets
        } do %>
        You've bought <strong> <%= pluralize(curr_tickets, 'ticket') %> </strong> 
        and can still buy <strong> <%= max_tickets - curr_tickets %> </strong> more. 
        <% end %>
        <p>Tickets are bound by our <%= link_to "terms and conditions", '#' %>.</p>
        <%= form_tag(tickets_path, method: "post", role: 'form') do %>
          <div id="ticketForm">
          </div>
        <% end %>
      <% end %>
    </div>
    <% if curr_tickets != 0 %>
      <div class="col-sm-5">
        <h3> Purchased tickets (<%= curr_tickets %>) </h3>
        <ol class="tickets">
          <%= render current_user.tickets %>
        </ol>
      </div>
    <% end %>
  </div>
</div>