config/routes.rb
Railstest::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  resources :tickets
  
    
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  namespace :admin do
    root "base#index"

    resources :users do
      resources :tickets, only: [:new, :create]
    end

    resources :tickets, except: [:new, :create]
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @last_ticket_purchases = Ticket.last_ticket_purchases(10)
    @user_count = User.users_count 
    @ticket_count = Ticket.count

  end
end

app/views/admin/base/index.html.erb
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-6">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{@user_count} users" %></small></h4>
    <h4><%= link_to "Tickets", admin_tickets_path %> <small>- <%= "#{@ticket_count} tickets" %></small></h4>
    <hr/>
  </div>
  
  <div class="col-sm-6">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <h3>Last Ticket Purchases</h3>
    <ul class="list-unstyled">
      <% @last_ticket_purchases.each do |ticket| %>
      <li class="list-padded-bottom">
        <%= link_to ticket.user.email, edit_admin_ticket_path(ticket) %><br/>
        <small><%= time_ago_in_words(ticket.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-6">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>
</row>