config/routes.rb
Railstest::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  resources :tickets
  
    
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  namespace :admin do
    root "base#index"

    resources :users do
      resources :tickets, only: [:new, :create]
    end

    resources :tickets, except: [:new, :create]
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Capitalize

  # Maximum number of tickets permittable
  MAX_TICKETS = 4

  before_validation :capitalize_names
  after_update :subscribe_mailchimp
  after_save :unsubscribe_mailchimp
  before_destroy :unsubscribe_mailchimp

  has_many :tickets, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable, :async
         
  # Pagination
  paginates_per 100
  
  # Strip whitespaces
  auto_strip_attributes :email, :first_name, :last_name

  # Validations
  @@college_regex = /\A(.+)@(.+)\.ox\.ac\.uk\Z/  

  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_format_of :email, with: @@college_regex,  message: "must be from Oxford", unless: "admin? || external_email?"
  validates :first_name, :last_name, :college, presence: true
  validate :hughs_only_if_email, unless: "admin? || external_email?"
  
  def hughs_only_if_email
    if !email then return end
    match = email.match(@@college_regex)
    if match then email_college = match[2] else email_college = "" end
    errors.add(:base, "Email isn't from Hugh's") if (college == "st-hughs") && (email_college != "st-hughs")
  end

  def external_email?
    return self.external_email
  end

  def self.paged(page_number)
    order(admin: :desc, email: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      q = "%#{search}%"
      where("email LIKE ? OR first_name LIKE ? or last_name LIKE ? or college LIKE ?", q, q, q, q).order(
      admin: :desc, email: :asc
      ).page page_number
    else
      order(admin: :desc, email: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","email","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","email","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end

  private
   def unsubscribe_mailchimp
     if self.tickets.length > 0
       # has purchased tickets previously, so let's remove
       MailchimpUnsubscriber.perform_async(self.email_was, "post_purchase_list")
     end
   end

   def subscribe_mailchimp
     if self.tickets.length > 0
       # has purchased tickets previously, so let's add again
       MailchimpSubscriber.perform_async(self.id, "post_purchase_list")
     end
   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_user_path(params[:id])
  end
  
  def edit
  end

  def new
    @user = User.new
  end

  def create
    @college_regex = /\A(.+)@(.+)\.ox\.ac\.uk\Z/

    # if is Oxford email, set external_email to false; else, true.
    if @college_regex.match(user_params[:email])
      @user = User.new(user_params)
    else
      @user = User.new(user_params.merge(external_email: true))
    end

    if @user.valid?
      @user.skip_confirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} created."
    else
      @errors = @user.errors
      flash.now[:error] = @errors.full_messages[0]
      render 'new'
    end
  end
  
  def update
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip
    
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    @user.first_name = new_params[:first_name]
    @user.last_name = new_params[:last_name]
    @user.college = new_params[:college]

    
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end
    
    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      @errors = @user.errors
      flash.now[:error] = @errors.full_messages[0]
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "#{@user.email} deleted."
    redirect_to admin_users_path
  end
  
  private 
  
  def set_user
    @user = User.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end
  
  def user_params
    params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :first_name,
    :last_name,
    :college,
    :admin,
    :locked
    )
  end
  
end

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1>
      Edit User <small><%= "#{@user.email} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-8">      
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :first_name %>
      <div class="row">
        <div class="col-sm-8">
          <%= f.text_field :first_name,  class: "form-control", id:"firstNameField" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <div class="row">
        <div class="col-sm-8">
          <%= f.text_field :last_name,  class: "form-control", id:"lastNameField"%>
        </div>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :college %>
      <div class="row">
        <div class="col-sm-8">
          <%= f.select(:college, options_for_college, {},  {class: "form-control"})%>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-8">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <% unless current_user.id == @user.id %>
    <div class="checkbox form-group">
      <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
    </div>
    
    <div class="checkbox form-group">
      <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
    </div>    
    <% end %>

    <div class="row">
      <div class="col-sm-8">
        <p>
          <%= f.submit "Update user", class: "btn btn-primary" %>
        </p>
      </div>
    </div>    
    
    <div class="row">
      <div class="col-sm-12">
        <p>
          <%= link_to("Add ticket", "/admin/users/#{@user.id}/tickets/new", class: "btn btn-primary") %>
        </p>
      </div>
    </div>    

    <div class="row">
      <div class="col-sm-8">
        <p>
          <%= link_to("Delete user", "/admin/users/#{@user.id}", method: :delete, class: "btn btn-danger") %>
        </p>
      </div>
    </div>    
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<div class="row">
  <div class="col-sm-10">
    <%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
        <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
      </p>
    <% end %>
  </div>
  <div class="col-sm-2">
    <%= link_to "Add user", new_admin_user_path, { class: "btn  btn-sm btn-primary", style: "float: right;" } %>
  </div>
</div>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Email</th>
    <th>Tickets</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>College</th>
    <th>Admin</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
  </tr>
  
  <% @users.each do |user| %>
  
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.email, admin_user_path(user) %></td>
    <td><%= link_to user.tickets.size, "tickets?search=#{user.email}" %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to user.college, "http://www.#{user.college}.ox.ac.uk" %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
  </tr>
  
  <% end %>
  
</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/admin/users/new.html.erb
<%= javascript_include_tag "registration" %>
<div class="row">
  <div class="col-sm-8">
    <h1>Add user</h1>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

      <div class="form-group">
        <%= f.label :email %> <i><small>(Oxford preferred, if available) </small></i>
        <div class="row">
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", id:"emailField" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :first_name %>
        <div class="row">
          <div class="col-sm-8">
            <%= f.text_field :first_name, class: "form-control", id:"firstNameField" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <div class="row">
          <div class="col-sm-8">
            <%= f.text_field :last_name, class: "form-control", id:"lastNameField" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :college %>
        <div class="row">
          <div class="col-sm-8">
            <%= f.select(:college, options_for_college, {},  {class: "form-control"})%>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-8">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-8">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-8">
          <%= f.submit "Add user", class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>



    </div>
  </div>